# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_remove_tag_link'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(to='tagging.Tag'),
        ),
    ]
